### ISSUE TITLE
BSD-derived shows as "Unnecessary safe licenses listed" AND "unsafe"

### ISSUE THREAD

**Issue by lexicalunit** [ubersan/pylic#83]
I get the following output:
```
$ poetry run pylic check
Unnecessary safe licenses listed which are not used by any installed package:
  BSD-derived
Found unsafe licenses:
  supervisor (4.2.2): BSD-derived (http://www.repoze.org/LICENSE.txt)
  ...
```

Even tho I have this licence specically listed as safe in my `pyproject.toml`:

```
[tool.pylic]
safe_licenses = [
  "BSD License",
  "BSD-derived",
  ...
]
```

**Comment by lexicalunit** [comment]
Ah, I needed to use `BSD-derived (http://www.repoze.org/LICENSE.txt)` as the license name... that feels weird though. Am I doing something wrong here?

**Comment by ubersan** [comment]
Hi @lexicalunit 

Glad you figured it out and got it working. Based on the `pylic check` output your actions are correct. I agree that this feels quite weird.

In this case the problem is as follows:
- `pylic` tries to read the license from 2 sources in this order: First from the classifiers and if and only if none has been found from the metadata. The reason for this is that these classifiers are specified by [PEP 301](https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification) and are a fixed set of strings: https://pypi.org/classifiers/. This is also true for all license classifiers, which makes license matching/tracking/comparing a lot easier.  See e.g. the [pylic](https://pypi.org/project/pylic/) pypi project on the left side the `Classifier` entries: it contains a `License` entry listing the corresponding license (`MIT License`). It also provides a `Meta` entry with `License` set to `MIT License (MIT)`.
- The [supervisor](https://pypi.org/project/supervisor/) package though does not provide such a classifier, which is why `pylic` falls back to the `Meta` entry, which is basically free text and there you can see this `BSD-derived (http://www.repoze.org/LICENSE.txt)` license. I can't seem to reach http://www.repoze.org/LICENSE.txt, so I guess this is outdated.

It thus seems to me that the licensing of this project is outdated and the project should if possible move either to a classifier-based license (e.g. `License :: OSI Approved :: BSD License`) or add a more sensible `Meta` license entry.

I hope this makes sense :smile: else please follow-up!

Regarding the weird license string there is currently no alternative as long as the `supervisor` maintainers don't tackle this issue on their end - sorry.
